cmdb/cmdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

cmdb/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<host_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<host_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^search_form', views.search_form, name='search_form'),
    url(r'^search', views.search, name='search'),
]

cmdb/polls/models.py
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Host(models.Model):
    # position = models.ForeignKey(Position, on_delete=models.CASCADE)
    hostname =models.CharField(max_length=25,null=False,unique=True)
    ipaddress01 = models.CharField(max_length=16,null=False,unique=True)
    ipaddress02 = models.CharField(max_length=16,blank=True,null=True,unique=True)
    vip = models.CharField(max_length=16,blank=True,null=True,unique=True)
    remark = models.CharField(max_length=16,blank=True,null=True)

    def __str__(self):
        return self.hostname
    def get_host(self):
        host = []
        if self.ipaddress02:
            host = [self.hostname,self.ipaddress01,self.ipaddress02]
        else:
            host = [self.hostname,self.ipaddress01]
        if self.vip:
            host = [self.hostname,self.ipaddress01,self.vip]
        if self.ipaddress01 and self.ipaddress02 and self.vip:
            host = [self.hostname,self.ipaddress01,self.ipaddress02,self.vip]
        return host

@python_2_unicode_compatible
class Position(models.Model):
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    province = models.CharField(max_length=10,null=False)
    city = models.CharField(max_length=10,null=False)
    serverroom = models.CharField(max_length=10,null=False)
    cabinet = models.CharField(max_length=10,null=False)
    remark = models.CharField(max_length=20,blank=True,null=True)

    def __str__(self):
        position = []
        position = [self.province,self.city,self.serverroom,self.cabinet]
        return ''.join(position)




@python_2_unicode_compatible
class User(models.Model):
    # operate = models.ForeignKey(Operate)
    ROLE_CHOICE = (
        (0,'admin'),
        (1,'guest'),
    )
    role = models.IntegerField(choices=ROLE_CHOICE)
    name = models.CharField(max_length=10,unique=True,null=False)
    password = models.CharField(max_length=25,null=False)
    mail = models.CharField(max_length=25,unique=True,null=False)

    def __str__(self):
        return self.name

    def get_user(self):
        user = []
        user = [self.name,self.role,self.mail]
        return user

@python_2_unicode_compatible
class Operate(models.Model):
    host = models.ForeignKey(Host)
    user = models.ForeignKey(User)
    position = models.ForeignKey(Position)
    STATUS_CHOICE = (
        (0 ,'online'),
        (1 , 'offline'),
    )
    status = models.IntegerField(choices=STATUS_CHOICE)
    log = models.TextField(max_length=1000)
    timestamp = models.DateTimeField('Operate Time')
    remark = models.CharField(max_length=20,blank=True,null=True)

    def __str__(self):
        return self.log

    def get_host_status(self):
        return self.status

cmdb/polls/forms.py
from django import forms
class NameForm(forms.Form):
    name = forms.CharField(label='name', max_length=50)

cmdb/polls/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# from django.views import generic
from django.utils import timezone

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.template import loader
from .models import Host, Operate, Position, User
from .forms import NameForm


def index(request):
    # host_list = Host.objects.order_by('hostname')[:5]
    host_list = Host.objects.order_by('hostname')
    paginator = Paginator(host_list, 1)

    page = request.GET.get('page')
    try:
        host = paginator.page(page)
    except PageNotAnInteger:
        host = paginator.page(1)
    except EmptyPage:
        host = paginator.page(page.num_pages)
    context = {'host_list': host}
    return render(request, 'polls/index.html', context)


def detail(request, host_id):
    host = get_object_or_404(Host, pk=host_id)
    return render(request, 'polls/detail.html', {'host': host})


def results(request, host_id):
    host = get_object_or_404(Host, pk=host_id)
    return render(request, 'polls/results.html', {'host': host})


def search_form(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
    else:
        form = NameForm()
    return render(request, 'polls/search_form.html', {'form': form})


def search(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            results = Host.objects.filter(hostname__contains=name).values()
        else:
            requests = Host.objects.all()[:5]
    else:
        name = request.GET.get('name')
        results = Host.objects.filter(hostname__contains=name).values()

    paginator = Paginator(results, 1)
    page = request.GET.get('page')
    # print(page)
    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(page.num_pages)
    context = {'result_list': result, 'name': name}
    return render(request, 'polls/search.html', context)

cmdb/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="utf-8">
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<head>
    <!--<link rel="stylesheet" type="text/css" href='polls/style.css' />-->
    <title>{% block title %}CMDB{% endblock %}</title>
</head>


<body>
<div id="sidebar">
    {% block sidebar %}
    <ul class="nav nav-pills  nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="/polls/">Home</a></li>
        <li role="presentation"><a href="/admin">Admin</a></li>
        <li role="presentation"><a href="/polls/">CMDB</a></li>
        <li role="presentation"><a href="/polls/search_form.html">Search</a></li>
        <!--<li role="presentation"><a href="search_form.html">Search_Form</a></li>-->
    </ul>
    {% endblock %}
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

cmdb/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block title %}CMDB{% endblock %}
{% block content %}

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}


{% for position in host.position_set.all %}
{% for operate in host.operate_set.all %}
<div>
    <table class="table table-hover">
        <tr>
            <td>主机名</td>
            <td>位置</td>
            <td>操作日志</td>
            <td>日期</td>
        </tr>
        <tr>
            <td>{{ host }}</td>
            <td>{{ position }}</td>
            <td>{{ operate }}</td>
            <td>{{ operate.timestamp |date:"Y-m-d" }}</td>
        </tr>
    </table>
</div>
{% endfor %}
{% endfor %}
{% endblock %}

cmdb/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %}CMDB{% endblock %}
{% block content %}
{% if host_list %}
<div class="table-responsive ">
    <table width="700" border="0.5" cellpadding="5" class="table table-hover">
        <tr class="active">
            <th width="80">主机名</th>
            <th width="80">IP01</th>
            <th width="80">IP02</th>
            <th width="80">VIP</th>
            <th width="80">说明</th>
        </tr>
    </table>
    {% for host in host_list %}
    <table width="700" border="0.5" cellpadding="5" class="table table-hover">
        <td class="success" width="80"><a href="/polls/{{ host.id }}/">{{ host.hostname }} </a></td>
        <td class="success" width="80">{{ host.ipaddress01 }}</td>
        <td class="success" width="80">{{ host.ipaddress02 }}</td>
        <td class="success" width="80">{{ host.vip }}</td>
        <td class="success" width="80">{{ host.remark }}</td>

    </table>
    {% endfor %}
</div>
{% else %}
<p>No polls are available.</p>
{% endif %}


<div class="pagination">
<nav>
    <ul class="pager">
    <span  class="label label-info" >
        {% if host_list.has_previous %}
        <li>
            <a href="?page={{ host_list.previous_page_number }}">上一页</a>
        </li>
        {% endif %}

        <span >
            <li >Page {{ host_list.number }} of {{ host_list.paginator.num_pages }}</li>
        </span>

        {% if host_list.has_next %}
        <li>
            <a href="?page={{ host_list.next_page_number }}">下一页</a>
        </li>
        {% endif %}
    </span>
    </ul>
</nav>
</div>

{% endblock %}

cmdb/polls/templates/polls/results.html
<h1>{{ host.hostname }}</h1>

<ul>
    {% for choice in host.choice_set.all %}
    <li>{{ choice.hosname }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' host.id %}">Vote again?</a>

cmdb/polls/templates/polls/search.html
{% extends 'polls/base.html' %}
{% block title %}CMDB{% endblock %}
{% block content %}
<p>{{ results }}</p>
{% if result_list %}
<div class="table-responsive ">
    <table width="700" border="0.5" cellpadding="5" class="table table-hover">
        <tr class="active">
            <th width="80">主机名</th>
            <th width="80">IP01</th>
            <th width="80">IP02</th>
            <th width="80">VIP</th>
            <th width="80">说明</th>
        </tr>
    </table>
    {% for host in result_list %}
    <table width="700" border="0.5" cellpadding="5" class="table table-hover">
        <td class="success" width="80">{{ host.hostname }}</td>
        <td class="success" width="80">{{ host.ipaddress01 }}</td>
        <td class="success" width="80">{{ host.ipaddress02 }}</td>
        <td class="success" width="80">{{ host.vip }}</td>
        <td class="success" width="80">{{ host.remark }}</td>
    </table>
    {% endfor %}
</div>
{% endif %}

<div class="pagination">
<nav>
    <ul class="pager">
    <span  class="label label-info" >
        {% if result_list.has_previous %}
        <li>
            <a href="?page={{ result_list.previous_page_number }}&name={{name}}">上一页</a>
        </li>
        {% endif %}

        <span >
            <li >Page {{ result_list.number }} of {{ result_list.paginator.num_pages }}.</li>
        </span>

        {% if result_list.has_next %}
        <li>
            <a href="?page={{ result_list.next_page_number }}&name={{name}}">下一页</a>
        </li>
        {% endif %}
    </span>
    </ul>
</nav>
</div>
{% endblock %}

cmdb/polls/templates/polls/search_form.html
{% extends 'polls/base.html' %}
{% block title %}CMDB{% endblock %}
{% block content %}

<form action="search.html" class="navbar-form navbar-right" role="search" method="get">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn-primary">Search</button>
</form>
{% endblock %}